// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8AhVQrfF5CuQ57y0ZP22dmGslX5mHM-Q',
    appId: '1:496417231260:web:1f07ad2b555ae858cd3859',
    messagingSenderId: '496417231260',
    projectId: 'fir-authentication-77ad5',
    authDomain: 'fir-authentication-77ad5.firebaseapp.com',
    storageBucket: 'fir-authentication-77ad5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR4sioLDIyOyE9v_5Ev7IcWOm1DvbE0yg',
    appId: '1:496417231260:android:c3c1e782ea72ac32cd3859',
    messagingSenderId: '496417231260',
    projectId: 'fir-authentication-77ad5',
    storageBucket: 'fir-authentication-77ad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArXMGsLG6lm114iQreY7zkgcNvL-mUA70',
    appId: '1:496417231260:ios:3460a069c65bc828cd3859',
    messagingSenderId: '496417231260',
    projectId: 'fir-authentication-77ad5',
    storageBucket: 'fir-authentication-77ad5.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArXMGsLG6lm114iQreY7zkgcNvL-mUA70',
    appId: '1:496417231260:ios:205ae023d2cc87a8cd3859',
    messagingSenderId: '496417231260',
    projectId: 'fir-authentication-77ad5',
    storageBucket: 'fir-authentication-77ad5.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication.RunnerTests',
  );
}
